### ISSUE TITLE
how to download the dataset?

### ISSUE THREAD

**Issue by LeeTaiTai** [JACKYLUO1991/106-landmarks-dataset#3]

**Comment by actionLUO** [comment]
Sorry, the data set is no longer open source...

**Comment by soooohee** [comment]
> Sorry, the data set is no longer open source...
What date set do you use?

**Comment by soooohee** [comment]
> Sorry, the data set is no longer open source...


What date set do you use?????????

**Comment by JACKYLUO1991** [comment]
@soooohee face++ api
